---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      command: "yum install docker -y"
      command: "systemctl enable docker"
      command: "systemctl start docker"
      command: "yum install pip -y"
      command: "pip3 install docker-py"
