/*
 *****************************************************************************
    Copyright (c) Microsoft Corporation.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
    REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
    INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
    LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
    PERFORMANCE OF THIS SOFTWARE.
*****************************************************************************/
(function(O){var f=window.AmazonUIPageJS||window.P,K=f._namespace||f.attributeErrors,a=K?K("CardJsRuntimeBuzzCopyBuild",""):f;a.guardFatal?a.guardFatal(O)(a,window):a.execute(function(){O(a,window)})})(function(O,f,K){mix_d("@c/api-lock",["exports"],function(a){var c={},d=function(a){delete c[a.type]};a.default={isLockedFor:function(a){return!a.every(function(a){return!!c[a]})},unlockForEvent:function(a,b){c[a.type]=a;try{var e=b();if(e instanceof Promise)return e.finally?e.finally(function(){return d(a)}):
e.then(function(){return d(a)},function(b){d(a);throw b;});d(a)}catch(v){throw d(a),v;}return Promise.resolve()},unlockForEventOnce:function(a){c[a.type]=a},resetLocks:function(){Object.keys(c).forEach(function(a){return d(c[a])})}};a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-untrusted-ajax",["exports","tslib","@p/a-ajax","@c/guard"],function(a,c,d,e){function b(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function h(a){a=a&&a.http&&
a.http.getResponseHeader("Content-Type");if(!a)return"NO-CONTENT-TYPE-FOUND";a=a.split(",").map(function(a){return a.split(";")[0].trim()});return a.find(function(a){return"application/json"===a||"text/html"===a})||a[0]}function v(a,b){return{responseBody:b,contentType:h(a),xhr:a.http}}function f(a,b){return k["default"].promise(new Promise(function(d,e){var t=c.__assign(c.__assign({},b),{abort:function(){e("Ajax request aborted")},error:function(a,b){var c=a.http.status;200===c||202===c||204===c||
304===c?d(v(a,a.http.responseText)):(a=new r("Ajax request failed",a.http.status,b,a.http.status?K:"readyState: "+a.http.readyState+"."),e(a))},success:function(a,b,c){d(v(c,a))}});u["default"].ajax(a,t)}))}var u=b(d),k=b(e),p={contentType:"application/json"},r=function(a){function b(b,c,d,e){e=a.call(this,"["+c+" "+d+"] "+b+(e?". ":"")+(e||""))||this;e.responseMessage=b;e.statusCode=c;e.statusText=d;e.type="AjaxError";return e}c.__extends(b,a);return b}(Error);d=function(a,b,d){b=c.__assign(c.__assign({},
p),b);return f(a,{timeout:b.timeout,accepts:b.accepts,contentType:b.contentType,headers:b.additionalHeaders||{},params:d||{},paramsFormat:"json",method:"POST"})};e=function(a,b,d){b=c.__assign(c.__assign({},p),b);return f(a,{timeout:b.timeout,accepts:b.accepts,contentType:b.contentType,headers:b.additionalHeaders||{},params:d||{},method:"get",cache:!1})};var t={get:e,post:d};a.AjaxError=r;a.default=t;a.get=e;a.initialize=function(a,b,c){};a.post=d;Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@c/browser-operations","exports @c/guard @c/scoped-dom tslib @c/dom @c/api-lock @p/a-events @p/A @c/logger".split(" "),function(a,c,d,e,b,h,v,q,u){function k(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function p(a){return(a=a.getAttribute("data-mix-operations"))?a.trim():K}function r(a,b,g){m["default"].on(H[b],function(c){w["default"].unlockForEvent(c||{type:b},g.bind(null,{event:c,type:b,operationName:a,acknowledge:c&&c.acknowledge?function(){return c.acknowledge(document.body)}:
function(){},stopBubble:function(){throw Error("stopBubble not supported for global events");}}))})}function t(a){a.acknowledge=a.acknowledge||function(){};D.cards.filter(function(b){return b.ScopedDom.isAccessibleEvent(a)}).forEach(function(b){b.cardHandler(b.operations,b.ScopedDom.proxify(a),a)})}function B(a,g,c){var x=this,d=E(c).map(function(l){return J(A(l).map(function(b){return a[b]||[]})).filter(function(a){return a.eventType===c.type}).map(function(a){return function(){return e.__awaiter(x,
void 0,void 0,function(){var x,d=this;return e.__generator(this,function(n){switch(n.label){case 0:return x=!1,[4,w["default"].unlockForEvent(c,function(){return e.__awaiter(d,void 0,void 0,function(){var d;return e.__generator(this,function(n){switch(n.label){case 0:return n.trys.push([0,2,,3]),[4,a.callback({event:g,type:a.eventType,target:g.target,currentTarget:l,operationName:a.name,acknowledge:function(){return c.acknowledge(b.unscope(l))},stopBubble:function(){x=!0}})];case 1:return n.sent(),
[3,3];case 2:return d=n.sent(),y["default"].log(d),[3,3];case 3:return[2]}})})})];case 1:return n.sent(),[2,x]}})})}})});return J(d).reduce(function(a,b){return a.then(function(a){return a||b()})},Promise.resolve(!1))}function E(a){var b=a.target,c=[];if(a.eventPhase===Event.CAPTURING_PHASE)g(b)&&p(b)&&c.push(b);else for(;g(b);)p(b)&&c.push(b),b=b.parentElement;return c}function A(a){return(a=p(a))?a.split(/[\s,|]+/).reduce(function(a,b){0>a.indexOf(b)&&a.push(b);return a},[]):[]}function C(){return{define:function(a,
b,g){var c=z["default"].current(g);[].concat(b).forEach(function(b){I[b]?r(a,b,c):(n[a]=n[a]||[],n[a].push({name:a,eventType:b,callback:c}),0>D.listeners.indexOf(b)&&(document.addEventListener(b,t,!!G[b]),D.listeners.push(b)))})},attach:function(a,b){var g=b.getAttribute("data-mix-operations");g=g?g.split(" "):[];-1<g.indexOf(a)||g.push(a);b.setAttribute("data-mix-operations",g.join(" "))}}}var z=k(c),F=k(d),w=k(h),m=k(v);c=k(q);var y=k(u),D=f.mixBrowserOperationsState=f.mixBrowserOperationsState||
{listeners:[],cards:[]},G={focus:!0,blur:!0,mouseenter:!0,mouseleave:!0},I={orientationchange:!0,resize:!0,scroll:!0},H={orientationchange:c["default"].constants.BROWSER_EVENTS.ORIENTATION_CHANGE,resize:c["default"].constants.BROWSER_EVENTS.RESIZE,scroll:c["default"].constants.BROWSER_EVENTS.SCROLL},J=function(a){var b;switch(a.length){case 0:return a;case 1:return a[0];default:return(b=[]).concat.apply(b,e.__spread(a))}},g=function(a){return!!a&&a.nodeType===Node.ELEMENT_NODE&&F["default"].isAccessibleElement(a)},
n={};a.default={setup:C};a.initialize=function(a,b,g){D.cards.push({operations:n,cardHandler:B,ScopedDom:F["default"]})};a.setup=C;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/browser-window",["exports"],function(a){var c=function(){return{get devicePixelRatio(){return f.devicePixelRatio},get innerWidth(){return f.innerWidth},get innerHeight(){return f.innerHeight},get outerWidth(){return f.outerWidth},get outerHeight(){return f.outerHeight},get pageXOffset(){return f.pageXOffset},
get pageYOffset(){return f.pageYOffset},get screenX(){return f.screenX},get screenY(){return f.screenY},get scrollX(){return f.scrollX},get scrollY(){return f.scrollY}}},d=c();a.default=d;a.getWindow=c;a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@amzn/mix.client-runtime",["exports","tslib"],function(a,c){function d(a,b){void 0===b&&(b=function(a){});return setTimeout(function(){var c="Late loading module "+a;f.P.log(c,"WARN","MIX");b(c)},3E3)}function e(a){var b=
k,c=new Promise(function(a){b=a}),e=d(a);c.then(function(){return clearTimeout(e)});return{promise:c,resolve:b}}function b(a){u[a]||(u[a]=e(a));return u[a]}function h(a,d){return c.__awaiter(this,void 0,void 0,function(){function e(a){a in d||(d[a]=t(a));return d[a]}function t(a){return c.__awaiter(this,void 0,void 0,function(){var d,m,t,k,p;return c.__generator(this,function(c){switch(c.label){case 0:return[4,b(a).promise];case 1:return d=c.sent(),m=d.capabilities,p=t=d.cardModuleFactory,[4,Promise.all((m||
[]).map(e))];case 2:return k=p.apply(void 0,[c.sent()]),h.push(k),[2,k]}})})}var h,k;return c.__generator(this,function(b){switch(b.label){case 0:return h=[],[4,Promise.all(a.map(e))];case 1:return k=b.sent(),[2,{requestedOrder:k,initializationOrder:h}]}})})}function v(a,b){b="#"===b[0]?b.slice(1):b;if(b=document.getElementById(b))if(b.hasAttribute("data-mix-claimed"))a.log("Could not register card: Candidate root claimed","WARN","MIX");else return b.setAttribute("data-mix-claimed","true"),b;else a.log("Could not register card: Candidate root not found",
"WARN","MIX")}function q(a){a=a.getAttribute("data-model");if(!a)return K;try{return JSON.parse(a)}catch(B){throw Error("Unable to inflate seed ViewModel: "+B);}}var u={},k=function(){},p=function(a,b,c,d){return function(e){var k=b();e.filter(function(a){return a.initialize}).forEach(function(b){b.initialized||(b.initialize(a,k,c,d),b.initialized=!0);return b})}},r=function(a,b,d,e,k){void 0===k&&(k={});return c.__awaiter(void 0,void 0,void 0,function(){var p,t,v,m,u,f,r,I,H,J,g;return c.__generator(this,
function(n){switch(n.label){case 0:return[4,h(null!==(J=b.capabilities)&&void 0!==J?J:[],e)];case 1:return p=n.sent(),t=p.initializationOrder,v=p.requestedOrder,u=[],0!==a.indexOf("@")?[3,3]:[4,h([a],e)];case 2:return f=n.sent(),r=c.__read(f.requestedOrder,1),I=r[0],H=f.initializationOrder,m=I,u=H,[3,4];case 3:m=null!==(g=k[a])&&void 0!==g?g:k[a]=b.cardModuleFactory(v,d),n.label=4;case 4:return[2,{resolvedMod:m,capabilitiesToInitialize:c.__spread(u,t)}]}})})};a.registerCapabilityModule=function(a,
c){b(a).resolve(c)};a.registerCardFactory=function(a,b){return c.__awaiter(this,void 0,void 0,function(){var e,k,h,u,t,w,m,y,D,B,I=this;return c.__generator(this,function(H){switch(H.label){case 0:e={};if(k=b.require)u={},h=function(a,b,n){var g=d(a[0],function(){});k(a,function(d){return c.__awaiter(I,void 0,void 0,function(){var x,I,H,l,k;return c.__generator(this,function(M){switch(M.label){case 0:clearTimeout(g);x=a[0];if(!d.cardModuleFactory)return[3,5];M.label=1;case 1:return M.trys.push([1,
3,,4]),[4,r(x,d,h,e,u)];case 2:return I=M.sent(),H=I.resolvedMod,l=I.capabilitiesToInitialize,B(c.__spread([H],l)),b(H),[3,4];case 3:return k=M.sent(),n(k),[3,4];case 4:return[3,6];case 5:b(d),M.label=6;case 6:return[2]}})})},n)};return[4,r(a,b,h,e)];case 1:return t=H.sent(),w=t.resolvedMod,m=t.capabilitiesToInitialize,y=w.P,B=p(a,function(){return D},w,y),[2,new Promise(function(b,c){y.execute(function(){var g=v(y,a);g?(D=q(g),B(m),f.mixCardInitTimeouts&&clearTimeout(f.mixCardInitTimeouts[a]),(g=
w.card(D))&&g.then?g.then(function(){b()}).catch(function(a){y.log(a.message,"FATAL");c(a)}):b()):(f.mixCardInitTimeouts&&clearTimeout(f.mixCardInitTimeouts[a]),b())})})]}})})};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/csa",["exports","tslib"],function(a,c){a.callEventInstance=function(a,e){for(var b=[],d=2;d<arguments.length;d++)b[d-2]=arguments[d];(d=f.mix_csa_event)&&d(a).apply(void 0,c.__spread([e],b))};a.initialize=function(a,c,b){};Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@c/dom",["exports"],function(a){var c,d,e=[],b=function(a){return document.createElement(a)},h={createElement:b,get cardRoot(){return d},get container(){return c},get scopes(){return e}};a.cardRoot=function(){return d};a.container=function(){return c};a.createElement=b;a.default=h;a.initialize=function(a,b,h){a="#"===a[0]?a.slice(1):a;d=document.getElementById(a);if(!d)throw Error("No node found for dom initialization");c=d.parentNode;e=[d]};a.scopes=function(){return e};a.unscope=function(a){return a&&
a.__unscope__?a.__unscope__(h):a};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/guard",["exports","@c/logger"],function(a,c){var d=c&&"object"===typeof c&&"default"in c?c:{"default":c},e;c=function(a,b){return e.guardFatal(a,b)};var b=function(a,b){return e.guardError(a,b)},h=function(a){return e.guardCurrent(a)},f=function(a){return a.catch(function(a){d["default"].log(a.message);throw a;})},q={asFatal:c,asError:b,current:h,promise:f};a.asError=b;a.asFatal=c;a.current=h;a.default=
q;a.initialize=function(a,b,c,d){e=d};a.promise=f;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/logger",["exports"],function(a){var c,d=function(a,b,d){return a.message?c.logError(a,null,b,d):c.log(a,b,d)};a.default={log:d};a.initialize=function(a,b,d,f){c=f};a.log=d;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/metrics",["exports"],function(a){var c,d=function(a,b,c){return f.ue.count(a,b,c)},e=function(a,b,c,d){f.ue.event(a,b,c,d)},b=function(a,b,c,d){f.uet(a,b,c,d)},
h=function(a,b,c){f.uex(a,b,c)},v=function(){return v},q={count:d,event:e,uet:b,uex:h,get rid(){return c}};a.count=d;a.default=q;a.event=e;a.initialize=function(a,b,d){c=f.ue.rid};a.rid=v;a.uet=b;a.uex=h;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/navigation",["exports"],function(a){var c=function(a){f.location.assign(a)},d=function(){return{get hash(){return f.location.hash},get host(){return f.location.host},get hostname(){return f.location.hostname},get href(){return f.location.href},
get origin(){return f.location.origin},get pathname(){return f.location.pathname},get port(){return f.location.port},get protocol(){return f.location.protocol},get search(){return f.location.search}}};a.default={setLocation:c,getLocation:d};a.getLocation=d;a.initialize=function(a,b,c){};a.setLocation=c;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/remote-operations","exports @c/dom @c/aui-untrusted-ajax @c/guard @c/metrics @c/scoped-dom @c/scoped-metrics tslib".split(" "),function(a,
c,d,e,b,h,v,q){function u(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function k(a){var b=function(c){var d=b.trackingApplicable,l=b.trackingParams,e=b.trackingStandalone,m=g+a;if(x!==K){e&&(m+=-1!==m.indexOf("?")?"\x26track\x3dtrue":"/track");if(d){d=x;l=l||{};var L=l.refSuffix,k=l.ref_;l=q.__rest(l,["refSuffix","ref_"]);e=d.ref_||"";k=k||"";L=L||"";var J=e;k?J=k:L&&(k=e.match(D)||L.match(G),J=[e,L].join(k?"":"_"));e=(e=J)?{ref_:e}:{};d=q.__assign(q.__assign(q.__assign(q.__assign(q.__assign({},
H),d),l),e),I)}else d=x;d=d||{};l=[];for(var h in d)d.hasOwnProperty(h)&&(e=d[h],l.push(encodeURIComponent(h)+"\x3d"+encodeURIComponent(e)));m+=(-1!==m.indexOf("?")?"\x26":"?")+l.join("\x26")}N&&(m+=(-1!==m.indexOf("?")?"\x26":"?")+"stamp\x3d"+N);return w(m,a,c,n)};b.factoryClone=function(b){var c=k(a);b&&(c.trackingParams=b.trackingParams||{},c.trackingStandalone=b.trackingStandalone,c.trackingApplicable=b.trackingApplicable);return c};return b}function p(a,b){0<b.length&&b.forEach(function(b){a[b]=
k(b)})}function r(a){void 0===a&&(a=[]);p(L,a);return L}var t=u(c),B=u(d),E=u(e),A=u(b),C=u(h),z=u(v),F=function(a){return a&&"AjaxError"===a.type},w=function(a,b,c,g){a=B["default"].post(a,{accepts:"text/html, application/json",contentType:"application/json",additionalHeaders:{"x-amz-acp-params":g}},c);a.then(function(){m(b,"success")},function(a){if(F(a)){var c=a.statusCode;"Request Timeout"===a.statusText?m(b,"timeout"):m(b,"error",c)}else"Ajax request aborted"===a&&m(b,"abort")});return E["default"].promise(a.then(function(a){var b=
a.contentType;a=a.responseBody;if("application/json"===b)return a||{};if("text/html"===b)try{var c=(new DOMParser).parseFromString(a,"text/html").querySelector("body").firstElementChild;return C["default"].proxify(c,c)}catch(U){throw Error("Error encountered when parsing html response: "+U);}else throw Error("Unexpected content-type found when parsing response: "+b);}))},m=function(a,b,c){y(A["default"].count,"mix:remoteOperations",b,c);y(z["default"].count,"remoteOperations:"+a,b,c)},y=function(a,
b,c,g){"success"===c?a(b+":attempt",1):(a(b+":attempt",0),a(b+":error:"+(g||c),1))},D=/[-_]$/,G=/^[-_]/,I={hitType:"pageTouch",pageAssemblyType:"main"},H=(c=f.uept)?{"page-type":c.pageType,"sub-page-type":c.subPageType}:{},J=function(){return"Bad data-acp-tracking value."},g,n,x,N,L={};a.default={setup:r};a.initialize=function(a,b,c){if((a=t["default"].cardRoot)&&a.hasAttribute("data-acp-path")&&a.hasAttribute("data-acp-params")){g=a.getAttribute("data-acp-path")||"";b=a.getAttribute("data-acp-params")||
"";try{var d=document.createElement("textarea");d.innerHTML=b;n=0===d.childNodes.length?"":d.childNodes[0].nodeValue||""}catch(M){throw Error("Issue encountered while parsing card attributes when setting up RemoteOperations, error: "+M);}a.removeAttribute("data-acp-path");a.removeAttribute("data-acp-params");a.hasAttribute("data-acp-stamp")&&(N=a.getAttribute("data-acp-stamp")||"",a.removeAttribute("data-acp-stamp"))}else throw Error("Remote Operation capability requires card root node to exist and have attribute: data-acp-path \x26 data-acp-params");
a:{if(t["default"].cardRoot.hasAttribute("data-acp-tracking"))try{x=JSON.parse(t["default"].cardRoot.getAttribute("data-acp-tracking"));break a}catch(M){f.P.logError(M,M instanceof SyntaxError?""+J:null,"ERROR")}x=K}c._operationNames&&p(L,c._operationNames)};a.isAjaxError=F;a.setup=r;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/scoped-dom",["exports","tslib","@c/dom"],function(a,c,d){function e(a,b){return a instanceof HTMLElement||a instanceof Node?b&&b.contains(a)||t["default"].scopes.some(function(b){return b.contains(a)})||
!document.body.contains(a):!0}function b(a,b){if("undefined"===typeof Proxy||"undefined"===typeof Reflect)return a;var c=a instanceof HTMLElement||a instanceof Node?k():a instanceof HTMLCollection||a instanceof NodeList?r():a instanceof Event?u():void 0;e(a,b)?c&&(a[D]||(a[D]=new Proxy(a,c)),a=a[D]):a=null;return a}function h(a){return function(){for(var b=[],c=0;c<arguments.length;c++)b[c]=arguments[c];b=b.map(function(a){return"function"===typeof a?v(a):a!==K&&a.__unscope__?d.unscope(a):a});return a.apply(d.unscope(this),
b)}}function v(a){return a.__proxy||(a.__proxy=function(){for(var c=[],d=0;d<arguments.length;d++)c[d]=arguments[d];return a.apply(b(this),c.map(function(a){return b(a)}))})}function q(a){return function(b){if(b===t["default"])return a;throw Error("Unable to unscope event target, password does not match.");}}function u(){return{get:function(a,c){var d=Reflect.get(a,c);if(c===D)return d;var g=Object.getOwnPropertyDescriptor(a,c);return g&&!1===g.configurable&&!1===g.writable?d:"__unscope__"===c?q(a):
"function"===typeof d?p(d,a,c):b(d)}}}function k(){return{get:function(a,c){var d=Reflect.get(a,c);if(c===D)return d;var g=Object.getOwnPropertyDescriptor(a,c);if(g&&!1===g.configurable&&!1===g.writable)return d;if("ownerDocument"===c)return null;if("__unscope__"===c)return q(a);"closest"===c&&(d=E);return"function"===typeof d?p(d,a,c):b(d)},set:function(a,c,d){"string"===typeof c&&c.startsWith("on")&&"function"===typeof d?Reflect.set(a,c,function(a){d.call(b(this),b(a))}):Reflect.set(a,c,d);return!0}}}
function p(a,d,e){var g=d[G]=d[G]||{},n=g[e];if(!n){if("addEventListener"===e){var x=a;a=function(a,b,d){b="handleEvent"in b?c.__assign(c.__assign({},b),{handleEvent:v(b.handleEvent)}):b;return x.call(this,a,b,d)}}n=h(a);g[e]=n}return function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];return b(n.apply(d,a))}}function r(){return{get:function(a,c){var d=Reflect.get(a,c),g=Object.getOwnPropertyDescriptor(a,c);return g&&!1===g.configurable&&!1===g.writable?d:"number"===typeof c||"string"===
typeof c&&Number.isInteger(Number.parseInt(c,10))?b(d):"__unscope__"===c?q(a):d}}}var t=d&&"object"===typeof d&&"default"in d?d:{"default":d};f.mixCardIndex=f.mixCardIndex||0;var B=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector,E=Element.prototype.closest||function(a){var b=this;do{if(B.call(b,a))return b;b=b.parentNode}while(b);return null},A="body frame frameset head html iframe script style".split(" "),C=function(a){var c=b(a,a);t["default"].scopes.push(a);
return{root:c,validate:function(a){return a()},isAccessibleEvent:function(a){return e(a.target,c)}}},z=function(a){return e.apply(void 0,c.__spread([a.target],t["default"].scopes))},F=function(a){return e.apply(void 0,c.__spread([a],t["default"].scopes))},w=function(a){return a()},m=function(a){if(-1<A.indexOf(a))throw Error("The following element is not allowed to be created in cards: '"+a+"'.");a=document.createElement(a);return b(a)},y={get cardRoot(){return b(t["default"].cardRoot,t["default"].cardRoot)},
scopeElement:C,isAccessibleEvent:z,isAccessibleElement:F,validate:w,createElement:m,proxify:b},D,G;a.cardRoot=function(){return b(t["default"].cardRoot,t["default"].cardRoot)};a.createElement=m;a.default=y;a.initialize=function(a,b,c){a=f.mixCardIndex++;D="__proxified_"+a;G="__wrappedSafeMethods_"+a};a.isAccessibleElement=F;a.isAccessibleEvent=z;a.scopeElement=C;a.validate=w;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/scoped-metrics",["exports","tslib","@c/metrics","@c/dom"],function(a,
c,d,e){var b=e&&"object"===typeof e&&"default"in e?e:{"default":e},h=[];e=function(a,c){void 0===c&&(c="");var d=b["default"].cardRoot.parentElement;d&&d.classList.contains("celwidget")&&(c=(d.getAttribute("cel_widget_id")||d.getAttribute("data-cel-widget")||d.getAttribute("id"))+c,a.setAttribute("cel_widget_id",c),a.setAttribute("data-cel-widget",c),d.classList.contains("c-f")&&a.classList.add("c-f"),a.classList.add("celwidget"))};var f=function(a,b,c){h.forEach(function(e){d.count(e+":"+a,b,c)})},
q={count:f,instrumentCel:e};a.count=f;a.default=q;a.initialize=function(a,d,e){if(a=b["default"].cardRoot.getAttribute("data-card-metrics-id"))a=c.__read(a.split("_",1),1)[0],h.push(a)};a.instrumentCel=e;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/siege",["exports"],function(a){var c=function(a,b){return a.factoryClone({trackingParams:{sif_profile:b},trackingApplicable:!0})},d={applySifProfile:c};a.applySifProfile=c;a.default=d;a.initialize=function(a,b,c){};Object.defineProperty(a,
"__esModule",{value:!0})});mix_d("@c/sudo",["exports"],function(a){a.default={get cardRoot(){return null}};a.initialize=function(a,d,e){};a.sudo={};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/timing",["exports","tslib","@c/dom"],function(a,c,d){var e=d&&"object"===typeof d&&"default"in d?d:{"default":d},b,h;a.CARD_METRICS_ID_KEY="data-card-metrics-id";a.CEL_WIDGET_KEY="cel_widget_id";a.INSTANCE_ID_KEY="id";a.callEventInstance=function(a,b){for(var d=[],e=2;e<arguments.length;e++)d[e-
2]=arguments[e];(e=f.mix_csa_event)&&e(a).apply(void 0,c.__spread([b],d))};a.initialize=function(a,c,d){b=e["default"].cardRoot?e["default"].cardRoot.getAttribute("id"):null;h=e["default"].cardRoot?e["default"].cardRoot.getAttribute("data-card-metrics-id"):null};a.markFunctional=function(){var a=f.mix_csa;a&&h&&a('[cel_widget_id\x3d"'+h+'"]',"#"+b)("mark","functional")};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/tracking",["exports","tslib","@c/dom","@c/logger","@c/remote-operations"],
function(a,c,d,e,b){function h(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var f=h(d),q=h(e),u=h(b),k={missingAcpTrackingValue:function(){return"Missing data-acp-tracking."}},p=function(){if(!f["default"].cardRoot.hasAttribute("data-acp-tracking")){var a=k.missingAcpTrackingValue();q["default"].log(Error(a),"FATAL");return!1}return!0},r=function(a,b,c){void 0===b&&(b={});void 0===c&&(c=!1);return a.factoryClone({trackingParams:b,trackingStandalone:c,trackingApplicable:!0})};d=
function(a,b,d){void 0===b&&(b={});var e=u["default"].setup([a]);return p()?r(e[a],c.__assign(c.__assign({},b),{refSuffix:d}),!0):e[a]};e=function(a,b,d){void 0===b&&(b={});return p()?r(a,c.__assign(c.__assign({},b),{refSuffix:d})):a};b={createTracking:d,addTracking:e};a.addTracking=e;a.createTracking=d;a.default=b;a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/weblabs",["exports"],function(a){var c=function(a,c,b){f.ue.trigger(a,c,b)};a.default={trigger:c};
a.initialize=function(a,c,b){};a.trigger=c;Object.defineProperty(a,"__esModule",{value:!0})});(function(){var a=function(a,b,c){mix_d(a,b,c)};a.amd=!0;var c,d,e,b,h,f,q,u,k,p,r,t,B,E,A,C,z,F,w,m,y,D,G;(function(b){function c(a,b){a!==d&&("function"===typeof Object.create?Object.defineProperty(a,"__esModule",{value:!0}):a.__esModule=!0);return function(c,d){return a[c]=b?b(c,d):d}}var d="object"===typeof global?global:"object"===typeof self?self:"object"===typeof this?this:{};"function"===typeof a&&
a.amd?a("tslib",["exports"],function(a){b(c(d,c(a)))}):"object"===typeof module&&"object"===typeof module.exports?b(c(d,c(module.exports))):b(c(d))})(function(a){var H=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};c=function(a,b){function c(){this.constructor=a}H(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)};d=Object.assign||function(a){for(var b,
c=1,d=arguments.length;c<d;c++){b=arguments[c];for(var g in b)Object.prototype.hasOwnProperty.call(b,g)&&(a[g]=b[g])}return a};e=function(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var g=0;for(d=Object.getOwnPropertySymbols(a);g<d.length;g++)0>b.indexOf(d[g])&&Object.prototype.propertyIsEnumerable.call(a,d[g])&&(c[d[g]]=a[d[g]])}return c};b=function(a,b,c,d){var g=arguments.length,
e=3>g?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,n;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(a,b,c,d);else for(var l=a.length-1;0<=l;l--)if(n=a[l])e=(3>g?n(e):3<g?n(b,c,e):n(b,c))||e;return 3<g&&e&&Object.defineProperty(b,c,e),e};h=function(a,b){return function(c,d){b(c,d,a)}};f=function(a,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(a,b)};q=function(a,b,c,d){function g(a){return a instanceof c?a:
new c(function(b){b(a)})}return new (c||(c=Promise))(function(c,e){function l(a){try{x(d.next(a))}catch(R){e(R)}}function n(a){try{x(d["throw"](a))}catch(R){e(R)}}function x(a){a.done?c(a.value):g(a.value).then(l,n)}x((d=d.apply(a,b||[])).next())})};u=function(a,b){function c(a){return function(b){return d([a,b])}}function d(c){if(e)throw new TypeError("Generator is already executing.");for(;g;)try{if(e=1,n&&(l=c[0]&2?n["return"]:c[0]?n["throw"]||((l=n["return"])&&l.call(n),0):n.next)&&!(l=l.call(n,
c[1])).done)return l;if(n=0,l)c=[c[0]&2,l.value];switch(c[0]){case 0:case 1:l=c;break;case 4:return g.label++,{value:c[1],done:!1};case 5:g.label++;n=c[1];c=[0];continue;case 7:c=g.ops.pop();g.trys.pop();continue;default:if(!(l=g.trys,l=0<l.length&&l[l.length-1])&&(6===c[0]||2===c[0])){g=0;continue}if(3===c[0]&&(!l||c[1]>l[0]&&c[1]<l[3]))g.label=c[1];else if(6===c[0]&&g.label<l[1])g.label=l[1],l=c;else if(l&&g.label<l[2])g.label=l[2],g.ops.push(c);else{l[2]&&g.ops.pop();g.trys.pop();continue}}c=b.call(a,
g)}catch(T){c=[6,T],n=0}finally{e=l=0}if(c[0]&5)throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var g={label:0,sent:function(){if(l[0]&1)throw l[1];return l[1]},trys:[],ops:[]},e,n,l,m;return m={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(m[Symbol.iterator]=function(){return this}),m};k=function(a,b){for(var c in a)"default"===c||Object.prototype.hasOwnProperty.call(b,c)||G(b,a,c)};G=Object.create?function(a,b,c,d){d===K&&(d=c);Object.defineProperty(a,d,{enumerable:!0,get:function(){return b[c]}})}:
function(a,b,c,d){d===K&&(d=c);a[d]=b[c]};p=function(a){var b="function"===typeof Symbol&&Symbol.iterator,c=b&&a[b],d=0;if(c)return c.call(a);if(a&&"number"===typeof a.length)return{next:function(){a&&d>=a.length&&(a=void 0);return{value:a&&a[d++],done:!a}}};throw new TypeError(b?"Object is not iterable.":"Symbol.iterator is not defined.");};r=function(a,b){var c="function"===typeof Symbol&&a[Symbol.iterator];if(!c)return a;a=c.call(a);var d,g=[];try{for(;(void 0===b||0<b--)&&!(d=a.next()).done;)g.push(d.value)}catch(P){var e=
{error:P}}finally{try{d&&!d.done&&(c=a["return"])&&c.call(a)}finally{if(e)throw e.error;}}return g};t=function(){for(var a=[],b=0;b<arguments.length;b++)a=a.concat(r(arguments[b]));return a};B=function(){for(var a=0,b=0,c=arguments.length;b<c;b++)a+=arguments[b].length;a=Array(a);var d=0;for(b=0;b<c;b++)for(var e=arguments[b],m=0,f=e.length;m<f;m++,d++)a[d]=e[m];return a};E=function(a){return this instanceof E?(this.v=a,this):new E(a)};A=function(a,b,c){function d(a){n[a]&&(f[a]=function(b){return new Promise(function(c,
d){1<h.push([a,b,c,d])||e(a,b)})})}function e(a,b){try{var c=n[a](b);c.value instanceof E?Promise.resolve(c.value.v).then(g,m):l(h[0][2],c)}catch(V){l(h[0][3],V)}}function g(a){e("next",a)}function m(a){e("throw",a)}function l(a,b){(a(b),h.shift(),h.length)&&e(h[0][0],h[0][1])}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var n=c.apply(a,b||[]),f,h=[];return f={},d("next"),d("throw"),d("return"),f[Symbol.asyncIterator]=function(){return this},f};C=function(a){function b(b,
e){c[b]=a[b]?function(c){return(d=!d)?{value:E(a[b](c)),done:"return"===b}:e?e(c):c}:e}var c,d;return c={},b("next"),b("throw",function(a){throw a;}),b("return"),c[Symbol.iterator]=function(){return this},c};z=function(a){function b(b){e[b]=a[b]&&function(d){return new Promise(function(e,g){d=a[b](d);c(e,g,d.done,d.value)})}}function c(a,b,c,d){Promise.resolve(d).then(function(b){a({value:b,done:c})},b)}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var d=a[Symbol.asyncIterator],
e;return d?d.call(a):(a="function"===typeof p?p(a):a[Symbol.iterator](),e={},b("next"),b("throw"),b("return"),e[Symbol.asyncIterator]=function(){return this},e)};F=function(a,b){Object.defineProperty?Object.defineProperty(a,"raw",{value:b}):a.raw=b;return a};var v=Object.create?function(a,b){Object.defineProperty(a,"default",{enumerable:!0,value:b})}:function(a,b){a["default"]=b};w=function(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)"default"!==c&&Object.prototype.hasOwnProperty.call(a,
c)&&G(b,a,c);v(b,a);return b};m=function(a){return a&&a.__esModule?a:{"default":a}};y=function(a,b){if(!b.has(a))throw new TypeError("attempted to get private field on non-instance");return b.get(a)};D=function(a,b,c){if(!b.has(a))throw new TypeError("attempted to set private field on non-instance");b.set(a,c);return c};a("__extends",c);a("__assign",d);a("__rest",e);a("__decorate",b);a("__param",h);a("__metadata",f);a("__awaiter",q);a("__generator",u);a("__exportStar",k);a("__createBinding",G);a("__values",
p);a("__read",r);a("__spread",t);a("__spreadArrays",B);a("__await",E);a("__asyncGenerator",A);a("__asyncDelegator",C);a("__asyncValues",z);a("__makeTemplateObject",F);a("__importStar",w);a("__importDefault",m);a("__classPrivateFieldGet",y);a("__classPrivateFieldSet",D)})})();mix_d("@c/aui-bottom-sheet","exports tslib @c/logger @c/api-lock @c/dom @c/scoped-dom @p/a-events @p/A @p/a-sheet @c/guard @c/scoped-metrics".split(" "),function(a,c,d,e,b,h,v,q,u,k,p){function r(a){return a&&"object"===typeof a&&
"default"in a?a:{"default":a}}function t(){}function B(a,d,e){var m=this;void 0===e&&(e={});var g=C["default"].cardRoot.querySelector(d);d="@amzn/mix.client-cap.aui-bottom-sheet: Failed to call 'create' on bottom-sheet '"+a+"'.";if(!g)throw Error(d+" A root element is required. Cannot find a matched element by the given selector");if("function"===typeof getComputedStyle&&"none"!==getComputedStyle(b.unscope(g)).display)throw Error(d+" The sheet DOM root should be hidden initially. DOM root should use the AUI '.aok-hidden' class");
var f=a+"-"+I;if(w["default"].get(f))throw Error(d+" The sheet name '"+a+"' has already been used in this card. Choose a different one.");g.setAttribute("id",f);var h=w["default"].create(c.__assign(c.__assign({closeType:"icon"},e),{historySupportEnabled:!1,preloadDomId:g.id,name:f}));z["default"].one("a:sheet:beforeShow:"+f,function(){p.instrumentCel(b.unscope(g),"bottom-sheet-"+a)});var k=C["default"].scopeElement(b.unscope(g)).root,y=h._height;return D({getHeight:function(){return y},changeHeight:function(a){return new Promise(function(b){var c=
function(){y=h._height;b(!0)};z["default"].one("a:sheet:changeHeight:"+f,c);h.changeHeight({height:a})||(z["default"].off("a:sheet:changeHeight:"+f,c),b(!1))})},show:function(){return A["default"].isLockedFor(["click"])?(E["default"].log("Failed to call show because no click event was detected","FATAL"),Promise.resolve(!1)):new Promise(function(b){var c=function(){b(!0)};z["default"].one("a:sheet:afterShow:"+f,c);w["default"].showSheet(h)?p.count("bottomSheet:"+a+":show",1):(z["default"].off("a:sheet:afterShow:"+
f,c),p.count("bottomSheet:"+a+":show",0),b(!1))})},hide:function(){return A["default"].isLockedFor(["click"])?(E["default"].log("Failed to call hide because no click event was detected","FATAL"),Promise.resolve(!1)):new Promise(function(b){var c=function(){b(!0)};z["default"].one("a:sheet:afterHide:"+f,c);w["default"].hideSheet(h)?p.count("bottomSheet:"+a+":hide",1):(z["default"].off("a:sheet:afterHide:"+f,c),p.count("bottomSheet:"+a+":hide",0),b(!1))})},render:function(a){return c.__awaiter(m,void 0,
void 0,function(){var b,d,e=this;return c.__generator(this,function(l){switch(l.label){case 0:if(!h._animating)return[3,2];b=["a:sheet:afterShow:"+f,"a:sheet:afterHide:"+f,"a:sheet:changeHeight:"+f];return[4,new Promise(function(a){d=function(){a()};b.forEach(function(a){z["default"].one(a,d)})})];case 1:l.sent(),b.forEach(function(a){z["default"].off(a,d)}),l.label=2;case 2:return[2,new Promise(function(b){F["default"].requestAnimationFrame(function(){return c.__awaiter(e,void 0,void 0,function(){return c.__generator(this,
function(c){switch(c.label){case 0:return[4,a(k)];case 1:return c.sent(),b(),[2]}})})})})]}})})}},{beforeShow:"a:sheet:beforeShow:"+f,afterShow:"a:sheet:afterShow:"+f,beforeHide:"a:sheet:beforeHide:"+f,afterHide:"a:sheet:afterHide:"+f},t)}var E=r(d),A=r(e),C=r(h),z=r(v),F=r(q),w=r(u),m=r(k),y=function(a,b,c){return a.__wrapHandler?a.__wrapHandler:a.__wrapHandler=function(d){d=m["default"].current(a)(c?c(d,b):d);d instanceof Promise&&m["default"].promise(d)}},D=function(a,b,d){return c.__assign(c.__assign({},
a),{on:function(a,c){c=y(c,a,d);z["default"].on(b[a],c)},off:function(a,c){c=c.__wrapHandler;if(!c)throw Error("Unknown event handler!");z["default"].off(b[a],c)},once:function(a,c){c=y(c,a,d);z["default"].one(b[a],c)}})};f.mixCardIndex=f.mixCardIndex||0;var G;(function(a){a[a.Success=1]="Success";a[a.Failure=0]="Failure"})(G||(G={}));var I;d={create:B};a.create=B;a.default=d;a.initialize=function(a,b,c){I=f.mixCardIndex++};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-card",["exports",
"@p/a-cardui","@p/a-cardui-deck","@c/dom"],function(a,c,d,e){function b(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function f(a){var b=q["default"].get(e.unscope(a));return{isExpanded:function(){return b.isExpanded()},toggle:function(){return b.toggle()}}}function v(a){var b=u["default"].get(e.unscope(a));return{initializeAllCards:function(){return b.initializeAllCards()}}}var q=b(c),u=b(d);a.default={getCard:f,getCardDeck:v};a.getCard=f;a.getCardDeck=v;a.initialize=function(a,
b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-carousel","exports tslib @c/dom @p/a-carousel-framework @p/A @p/a-events @c/guard".split(" "),function(a,c,d,e,b,h,v){function q(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function u(a,b){return"change:pageNumber"===b?{newPageNumber:a.newValue,oldPageNumber:a.oldValue}:{}}function k(a,b){var e=this,f=b.strategies.display.repaint;return function(m,h){return c.__awaiter(e,void 0,void 0,function(){var e,k,g,
y,p;return c.__generator(this,function(c){switch(c.label){case 0:return[4,a({indexes:m,ids:h})];case 1:e=c.sent();"string"===typeof e&&(e=(new DOMParser).parseFromString(e,"text/html").body.children[0]);if(!e.classList.contains("a-carousel-content-fragment"))throw Error("CarouselRemoteOperation did not return a ContentFragment");k=Array.prototype.slice.call(e.querySelectorAll(".a-carousel-card-fragment")).map(function(a){return a.hasAttribute("data-a-delete")?null:d.unscope(a)});g=b.getAttr("ajax");
if(g.id_list&&h&&(y=m.filter(function(a,b){return null===k[b]}),y.length)){for(p=y.length-1;0<=p;p--)g.id_list.splice(y[p],1);b.setAttr("ajax",g);f&&t["default"].requestAnimationFrame(function(){f(b)})}return[2,k]}})})}}function p(a){var b=a.getAttr("name")||a.__id;if(0===b.indexOf("ciid"))return b;b="ciid-"+z+"-"+F+"-"+b;a.setAttr("name",b);return b}var r=q(e),t=q(b),B=q(h),E=q(v),A=function(a,b,c){return a.__wrapHandler?a.__wrapHandler:a.__wrapHandler=function(d){d=E["default"].current(a)(c?c(d,
b):d);d instanceof Promise&&E["default"].promise(d)}},C=function(a,b,d){return c.__assign(c.__assign({},a),{on:function(a,c){c=A(c,a,d);B["default"].on(b[a],c)},off:function(a,c){c=c.__wrapHandler;if(!c)throw Error("Unknown event handler!");B["default"].off(b[a],c)},once:function(a,c){c=A(c,a,d);B["default"].one(b[a],c)}})};f.mixCardIndex=f.mixCardIndex||0;var z,F;a.default={getCarousel:function(a){var b=r["default"].getCarousel(d.unscope(a)),c=p(b);return C({gotoPage:function(a){return b.gotoPage(a)},
gotoPrevPage:function(){return b.gotoPrevPage()},gotoNextPage:function(){return b.gotoNextPage()},get initialized(){return new Promise(function(a){return r["default"].onInit(c,function(){return a()})})},attachRemoteOperation:function(a){if(b.getAttr("async_provider"))throw Error("Carousel already has attached remoteOperation");b.setAttr("async_provider",k(a,b))}},{"change:pageNumber":"a:carousel:"+c+":change:pageNumber","change:fetchedItems":"a:carousel:"+c+":change:fetchedItems"},u)}};a.initialize=
function(a,b,c){z="#"===a[0]?a.slice(1):a;F=f.mixCardIndex++};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-feature-detect",["exports","@p/A"],function(a,c){var d=c&&"object"===typeof c&&"default"in c?c:{"default":c};c=function(a){return d["default"].capabilities[a]};a.default={isSupported:c};a.initialize=function(a,b,c){};a.isSupported=c;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-modal","exports tslib @p/a-modal @p/a-events @c/dom @c/scoped-dom @c/logger @c/scoped-metrics @c/aui-feature-detect @c/guard @c/api-lock".split(" "),
function(a,c,d,e,b,h,v,q,u,k,p){function r(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function t(){f.mixActiveModal=""}function B(a){if(""===f.mixActiveModal)f.mixActiveModal=a,y["default"].one("a:popover:invisible:"+a,t);else if(f.mixActiveModal!==a)throw Error(x.modalInUsed(f.mixActiveModal));}function E(){}function A(a){return a?a.substring(0,a.lastIndexOf("-"+N)):""}function C(a){return{beforeShow:"a:popover:beforeShow:"+a,afterShow:"a:popover:visible:"+a,beforeHide:"a:popover:beforeHide:"+
a,afterHide:"a:popover:invisible:"+a}}function z(a){return new Promise(function(b,c){f.P.when("a-popover-animate").execute(function(d){try{b(d.isAnimating(a))}catch(R){c(R)}})})}function F(a,d,e){var g=this;y["default"].one("a:popover:beforeShow:"+a,function(){q.instrumentCel(b.unscope(e),"modal-"+a)});var h=D["default"].scopeElement(b.unscope(e)).root;return n({id:a,show:function(){return c.__awaiter(g,void 0,void 0,function(){return c.__generator(this,function(b){return J["default"].isLockedFor(P)?
(G["default"].log(x.failToCallFor("show",A(a))+"  "+x.missingUserInteraction(P),"FATAL"),[2,Promise.resolve(!1)]):[2,new Promise(function(b){var c=function(){q.count("modal:"+A(a)+":show",1);b(!0)};y["default"].one(C(a).afterShow,c);try{B(a),d.show()}catch(Q){G["default"].log(x.failToCallFor("show",A(a))+" "+Q.message,"FATAL"),Q.message!==x.modalInUsed(f.mixActiveModal)&&f.mixActiveModal===a&&(y["default"].off("a:popover:invisible:"+a,t),t()),y["default"].off(C(a).afterShow,c),q.count("modal:"+A(a)+
":show",0),b(!1)}})]})})},hide:function(){return c.__awaiter(g,void 0,void 0,function(){return c.__generator(this,function(b){return J["default"].isLockedFor(P)?(G["default"].log(x.failToCallFor("hide",A(a))+"  "+x.missingUserInteraction(P),"FATAL"),[2,Promise.resolve(!1)]):[2,new Promise(function(b){var c=function(){b(!0)};y["default"].one(C(a).afterHide,c);try{d.hide()}catch(Q){G["default"].log(x.failToCallFor("hide",A(a))+" "+Q.message,"FATAL"),y["default"].off(C(a).afterHide,c),b(!1)}})]})})},
render:function(b){return c.__awaiter(g,void 0,void 0,function(){var e;return c.__generator(this,function(c){e=function(){return new Promise(function(c,e){try{b(h),d.isActive()&&d.updatePosition()}catch(S){G["default"].log(x.failToCallFor("render",A(a))+" "+S.message,"FATAL"),e(S)}c()})};return[2,z(d).then(function(b){if(!b)return e();var c=d.isActive()?C(a).afterShow:C(a).afterHide;return new Promise(function(a){y["default"].one(c,function(){a(e())})})})]})})}},C(a),E)}function w(a,d,e){d=D["default"].cardRoot.querySelector(d);
var f=x.failToCallFor("create",a);if(I["default"].isSupported("mobile"))throw Error(f+" "+x.unsupportedDevice("mobile"));if(!a)throw Error(f+" "+x.invalidName(a));if(m["default"].get(a+"-"+N))throw Error(f+" "+x.usedName(a));if(!d)throw Error(f+" "+x.unavailableRoot());if(A(d.getAttribute("data-a-modal-id")))throw Error(f+" "+x.usedRootOf(A(d.getAttribute("data-a-modal-id"))));if(!d.className.match(O))throw Error(f+" "+x.leakedRoot());var g=document.createElement("span");f=a+"-"+N;e=c.__assign(c.__assign({name:f,
popoverLabel:e.a11yOpenMessage,hideHeader:!0,closeButton:e.closeButton===K?!0:e.closeButton,padding:"none",legacyNavigable:!1},e.width?{width:e.width+"px"}:{}),e.height?{height:e.height+"px"}:{});e=m["default"].create(g,e);f=F(f,e,d);try{var h=e.attrs("name"),l=b.unscope(d),k=document.createElement("span");D["default"].cardRoot.appendChild(k);k.id="a-popover-"+h;k.className="a-popover-preload";k.appendChild(l);d.setAttribute("data-a-modal-id",h);d.className=d.className.replace(O,"")}catch(Q){throw Error(x.failToCallFor("create",
a)+" "+Q.message);}return f}var m=r(d),y=r(e),D=r(h),G=r(v),I=r(u),H=r(k),J=r(p),g=function(a,b,c){return a.__wrapHandler?a.__wrapHandler:a.__wrapHandler=function(d){d=H["default"].current(a)(c?c(d,b):d);d instanceof Promise&&H["default"].promise(d)}},n=function(a,b,d){return c.__assign(c.__assign({},a),{on:function(a,c){c=g(c,a,d);y["default"].on(b[a],c)},off:function(a,c){c=c.__wrapHandler;if(!c)throw Error("Unknown event handler!");y["default"].off(b[a],c)},once:function(a,c){c=g(c,a,d);y["default"].one(b[a],
c)}})},x={failToCallFor:function(a,b){return"@amzn/mix.client-cap.aui-modal: Failed to call '"+a+"' on modal '"+b+"'."},usedName:function(a){return"The modal name '"+a+"' has already been used in this card. Choose a different one."},unavailableRoot:function(){return"A root element is required. Cannot find a matched element by the given selector."},leakedRoot:function(){return"The modal DOM root should be hidden initially. DOM root should use the AUI '.aok-hidden' class."},usedRootOf:function(a){return"The root has already been bound to another modal, '"+
a+"'. Choose a different one."},invalidName:function(a){return"The modal name is invalid: "+a+"."},modalInUsed:function(a){return"Modal '"+a+"' is in use and should not be interrupted."},unsupportedDevice:function(a){return"Modal is only supported in desktop. Your card is in a "+a+" context."},missingUserInteraction:function(a){return"This operation can be only performed upon a user interaction of: "+a+". Browser Operation is the only recommended way over native event APIs."}};f.mixActiveModal=f.mixActiveModal||
"";f.mixCardIndex=f.mixCardIndex||0;var N,L;(function(a){a[a.Success=1]="Success";a[a.Failure=0]="Failure"})(L||(L={}));var O=/\baok-hidden\b/g,P=["click"];d={create:w};a.create=w;a.default=d;a.initialize=function(a,b,c){N=f.mixCardIndex++};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-truncate",["exports","@c/dom","@p/a-truncate"],function(a,c,d){function e(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function b(a){return k["default"].manualTruncate(a)}function f(){return k["default"].refreshAutoTruncate()}
function v(a){return k["default"].switchToAutoTruncate(a)}function q(){var a=u["default"].cardRoot.getElementsByClassName("a-truncate");Array.prototype.slice.call(a).forEach(function(a){return k["default"].get(c.unscope(a)).update()})}var u=e(c),k=e(d);a.default={manualTruncate:b,refreshAutoTruncate:f,switchToAutoTruncate:v,updateAll:q};a.initialize=function(a,b,c){};a.manualTruncate=b;a.refreshAutoTruncate=f;a.switchToAutoTruncate=v;a.updateAll=q;Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@c/aui-utils",["exports","@p/A","@c/dom"],function(a,c,d){function e(a){if(null===a||a===K)throw new TypeError("Value is null or undefined");}function b(a){w["default"].hide(d.unscope(a))}function f(a){w["default"].show(d.unscope(a))}function v(a){return w["default"].loadDynamicImage(d.unscope(a))}function q(a,b){return w["default"].onScreen(d.unscope(a),b)}function u(a){return w["default"].objectIsEmpty(a)}function k(a,b){return w["default"].equals(a,b)}function p(a,b){return w["default"].diff(a,
b)}function r(a,b,c){return w["default"].throttle(a,b,c)}function t(a,b,c){return w["default"].debounce(a,b,c)}function B(a){w["default"].defer(a)}function E(a,b){return w["default"].interval(a,b)}function A(a){return w["default"].animationFrameDelay(a)}function C(a,b){return w["default"].delay(a,b)}function z(a){return w["default"].once(a)}function F(a){return w["default"].attributionChain(d.unscope(a))}var w=c&&"object"===typeof c&&"default"in c?c:{"default":c};c={assertNotNullish:e,hide:b,show:f,
loadDynamicImage:v,onScreen:q,objectIsEmpty:u,equals:k,diff:p,throttle:r,debounce:t,defer:B,interval:E,animationFrameDelay:A,delay:C,once:z,attributionChain:F};a.animationFrameDelay=A;a.assertNotNullish=e;a.attributionChain=F;a.debounce=t;a.default=c;a.defer=B;a.delay=C;a.diff=p;a.equals=k;a.hide=b;a.initialize=function(a,b,c){};a.interval=E;a.loadDynamicImage=v;a.objectIsEmpty=u;a.onScreen=q;a.once=z;a.show=f;a.throttle=r;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/error-handling",
["exports"],function(a){var c,d=function(a,b,d,f){c.error(a,b,d,f)};a.default={error:d};a.error=d;a.initialize=function(a,b,d,f){c=f};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/pagemarker",["exports","@p/A","@c/dom","@c/guard"],function(a,c,d,e){function b(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function f(a){var b;return function(){return k["default"].promise(b=b||new Promise(function(b){return q["default"].on(a,function(){return b()})}))}}function v(a){void 0===
a&&(a=0);var b,c=new Promise(function(a){return b=a}),d=function(){q["default"].onScreen(u["default"].container,a)&&(q["default"].off("scroll resize ready",d),b())};q["default"].on("scroll resize ready",d);d();return c}var q=b(c),u=b(d),k=b(e),p=f("ready"),r=f("load");a.default={get pageReady(){return p()},get pageLoad(){return r()},visible:v};a.initialize=function(a,b,c){};a.pageLoad=function(){return r()};a.pageReady=function(){return p()};a.visible=v;Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@m/mash",["exports","@p/mash"],function(a,c){var d=c&&"object"===typeof c&&"default"in c?c:{"default":c},e;(function(a){a[a.DONE=0]="DONE";a[a.CANCEL=1]="CANCEL";a[a.SAVE=3]="SAVE";a[a.CLOSE=24]="CLOSE"})(e||(e={}));a.addEventListener=function(a,c){d["default"].addEventListener(a,c)};a.addition=function(a,c){console.log("Executing addition api in MASH client capability ");return a+c};a.androidUtil={callCallback:function(a,c,e){d["default"].android_util.callCallback(a,c,e)},removeCallback:function(a){d["default"].android_util.removeCallback(a)},
storeCallback:function(a,c){return d["default"].android_util.storeCallback(a,c)}};a.canLaunchIntentURL=function(a){d["default"].canLaunchIntentURL(a)};a.cancelFullscreen=function(a){d["default"].cancelFullscreen(a)};a.cart={didUpdate:function(a){d["default"].cart.didUpdate(a)}};a.dispatchEvent=function(a){d["default"].dispatchEvent(a)};a.exitEmbeddedBrowser=function(a){d["default"].exitEmbeddedBrowser(a)};a.goBack=function(a){d["default"].goBack(a)};a.initialize=function(a,c,d){};a.interactionMetrics=
{getRealClickTime:function(a){return d["default"].interactionMetrics.getRealClickTime(a)},send:function(a){return d["default"].interactionMetrics.send(a)}};a.iosUtil={callCallback:function(a,c,e){d["default"].ios_util.callCallback(a,c,e)},removeCallback:function(a){d["default"].ios_util.removeCallback(a)},storeCallback:function(a,c){return d["default"].ios_util.storeCallback(a,c)}};a.launchIntentURL=function(a){d["default"].launchIntentURL(a)};a.navigate=function(a){d["default"].navigate(a)};a.navstack=
{begin:function(){return d["default"].navstack.begin()},setBookmark:function(a){d["default"].navstack.setBookmark(a)},clearHistory:function(a){d["default"].navstack.clearHistory(a)},pageIsReadyToDisplay:function(a){d["default"].navstack.pageIsReadyToDisplay(a)}};a.openInExternalBrowser=function(a){d["default"].openInExternalBrowser(a)};a.permissions={requireForFeature:function(a){return d["default"].permissions.requireForFeature(a)},audit_execute:function(){d["default"].permissions.audit.execute()}};
a.privateAPI={getPushNotificationInfo:function(a){d["default"].privateAPI.getPushNotificationInfo(a)}};a.removeEventListener=function(a,c){d["default"].removeEventListener(a,c)};a.requestFullscreen=function(a){d["default"].requestFullscreen(a)};a.share=function(a){d["default"].share(a)};a.showAlert=function(a){d["default"].showAlert(a)};a.showContactPicker=function(a){d["default"].showContactPicker(a)};a.showEmbeddedBrowser=function(a){d["default"].showEmbeddedBrowser(a)};a.showImageGallery=function(a){d["default"].showImageGallery(a)};
a.showLoginDialog=function(a){d["default"].showLoginDialog(a)};Object.defineProperty(a,"__esModule",{value:!0})})});